server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    
    # THIS SERVES /data/published AS THE ROOT URL
    location / {
        alias /data/published/;
        autoindex on;
        index index.html index.htm;
    }

    location /health {
        access_log off;
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
}
